[workspace]
default-members = ["crates/aigw", "crates/aigw-console", "crates/aigw-core"]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = {version = "1"}
arc-swap = {version = "1.7"}
aya = {version = "0.14"}
aya-ebpf = {version = "0.2", default-features = false}
aya-log = {version = "0.3", default-features = false}
aya-log-ebpf = {version = "0.2", default-features = false}
base64 = {version = "0.22"}
cargo_metadata = {version = "0.23", default-features = false}
clap = {version = "4", features = ["derive", "std"]}
daemonize = {version = "0.5"}
dashmap = {version = "6"}
hex = {version = "0.4"}
hostname = {version = "0.4"}
http = {version = "1"}
lazy_static = {version = "1"}
libc = {version = "0.2"}
md5 = {version = "0.8"}
once_cell = {version = "1"}
pingora-cache = {version = "0.8"}
pingora-core = {version = "0.8", features = ["openssl"]}
pingora-error = {version = "0.8"}
pingora-http = {version = "0.8"}
pingora-limits = {version = "0.8"}
pingora-load-balancing = {version = "0.8"}
pingora-proxy = {version = "0.8"}
rustls = {version = "0.23"}
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}
sha = {version = "1"}
thiserror = {version = "2"}
time = {version = "0.3", features = ["formatting", "macros", "local-offset", "serde"]}
tracing-log = {version = "0.2"}
tokio = {version = "1", features = ["full"]}
tracing = {version = "0.1"}
tracing-appender = {version = "0.2"}
tracing-subscriber = {version = "0.3", features = ["env-filter", "fmt", "time"]}
which = {version = "6", default-features = false}

[profile.release.package.aigw-ebpf]
codegen-units = 1
debug = 2

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true