[package]
edition.workspace = true
name = "aigw-core"
version = "0.1.0"

[dependencies]
ahash = {version = "0.8"}
anyhow = {workspace = true}
base64 = {workspace = true}
byteorder = {version = "1"}
bytes = {version = "1"}
daemonize = {workspace = true}
http = {version = "1"}
lazy_static = {workspace = true}
libc = {workspace = true}
local-ip-address = {version = "0.6"}
pem = {version = "3"}
pingora-http = {workspace = true}
pingora-load-balancing = {workspace = true}
prost = {version = "0.13"}
protobuf = {version = "3"}
rcgen = {version = "0.14", features = ["aws_lc_rs"]}
regex = {version = "1"}
ring = {version = "0.17"}
rustls = {workspace = true}
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1"}
substring = {version = "1"}
sysinfo = {version = "0.37"}
thiserror = {version = "2"}
time = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
x509-parser = {version = "0.18"}

[build-dependencies]
prost-build = {version = "0.13"}
