use prost::Message;

use super::pb;

///
/// LogType includes Site, Cluster, Acme, and IpLayer4.
///
/// Among these, Site and Cluster are persistently stored: Site retains multiple entries, while Cluster keeps only a single entry.
///
#[derive(Clone, Debug, Copy, Hash, PartialEq, Eq)]
pub enum LogType {
    Cluster,
    Site,
    Acme,
    IpLayer4,
}

impl LogType {
    pub fn code(&self) -> u32 {
        match &self {
            LogType::Cluster => 1,
            LogType::Site => 2,
            LogType::Acme => 3,
            LogType::IpLayer4 => 4,
        }
    }

    pub fn all_types() -> Vec<LogType> {
        let types = vec![LogType::Site, LogType::Acme, LogType::IpLayer4];
        types
    }
}

impl TryFrom<u32> for LogType {
    type Error = anyhow::Error;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(LogType::Cluster),
            2 => Ok(LogType::Site),
            3 => Ok(LogType::Acme),
            4 => Ok(LogType::IpLayer4),
            _ => Err(anyhow::anyhow!("Unknow error.")),
        }
    }
}

#[derive(Clone, Debug, Copy)]
pub enum LogAction {
    Create,
    Update,
    Delete,
}

impl LogAction {
    pub fn code(&self) -> u32 {
        match &self {
            LogAction::Create => 1,
            LogAction::Update => 2,
            LogAction::Delete => 3,
        }
    }
}

impl TryFrom<u32> for LogAction {
    type Error = anyhow::Error;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(LogAction::Create),
            2 => Ok(LogAction::Update),
            3 => Ok(LogAction::Delete),
            _ => Err(anyhow::anyhow!("Unknow error.")),
        }
    }
}

#[derive(Clone, Debug, Copy)]
pub struct LogPoint {
    pub log_id: u64,
    pub log_type: LogType,
}

impl From<LogPoint> for pb::LogPoint {
    fn from(val: LogPoint) -> Self {
        pb::LogPoint {
            log_id: val.log_id,
            log_type: val.log_type.code(),
        }
    }
}

impl TryFrom<pb::LogPoint> for LogPoint {
    type Error = anyhow::Error;

    fn try_from(val: pb::LogPoint) -> Result<Self, Self::Error> {
        Ok(LogPoint {
            log_id: val.log_id,
            log_type: val.log_type.try_into()?,
        })
    }
}

/// Represents a change log entry that records modifications to data in the system.
///
/// This structure captures the essential information about a change operation including
/// the type of change, the target data, the action performed, and associated metadata.
/// The log data is stored as raw bytes to support flexible content types while maintaining
/// efficient storage and retrieval.
///
/// # Fields
/// - `log_id`: Unique identifier for this log entry, typically auto-generated by the database
/// - `cluster`: Name of the cluster where the change occurred, used for multi-tenant or sharded systems
/// - `log_type`: Categorizes the type of entity being logged (e.g., Site, Cluster, Acme, IpLayer4)
/// - `log_action`: Specifies the type of operation performed (Create, Update, Delete)
/// - `data_id`: Identifier of the specific data record that was modified
/// - `data`: Serialized data content in bytes, representing the actual payload of the change
///
/// # Notes
/// - The `data` field is stored as `Vec<u8>` to allow for flexible serialization formats
///   (JSON, MessagePack, Protobuf, etc.) depending on the application's needs
/// - This structure implements `Clone` and `Debug` traits for easy copying and debugging
/// - Log entries are typically managed by the change log system and not created directly
#[derive(Clone, Debug)]
pub struct ChangeLog {
    pub log_id: u64,
    pub cluster: String,
    pub log_type: LogType,
    pub log_action: LogAction,
    pub data_id: u64,
    pub data: Vec<u8>,
}

impl ChangeLog {
    pub fn to_vec(self) -> Vec<u8> {
        let pb: pb::ChangeLog = self.into();
        pb.encode_to_vec()
    }
}

impl TryFrom<&[u8]> for ChangeLog {
    type Error = anyhow::Error;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        let data = pb::ChangeLog::decode(value)?;
        data.try_into()
    }
}

impl From<ChangeLog> for pb::ChangeLog {
    fn from(val: ChangeLog) -> Self {
        Self {
            log_id: val.log_id,
            cluster_name: val.cluster,
            log_type: val.log_type.code(),
            log_action: val.log_action.code(),
            data_id: val.data_id,
            data: val.data,
        }
    }
}

impl TryFrom<pb::ChangeLog> for ChangeLog {
    type Error = anyhow::Error;

    fn try_from(val: pb::ChangeLog) -> Result<Self, Self::Error> {
        Ok(Self {
            log_id: val.log_id,
            cluster: val.cluster_name,
            log_type: val.log_type.try_into()?,
            log_action: val.log_action.try_into()?,
            data_id: val.data_id,
            data: val.data,
        })
    }
}

#[derive(Clone, Debug)]
pub struct DataFrame {
    pub logs: Vec<ChangeLog>,
    pub log_point: Option<LogPoint>,
}

impl DataFrame {
    pub fn new(logs: Vec<ChangeLog>, log_point: LogPoint) -> anyhow::Result<Self> {
        Ok(Self {
            logs,
            log_point: Some(log_point),
        })
    }
}

impl From<DataFrame> for pb::Data {
    fn from(val: DataFrame) -> Self {
        Self {
            logs: val.logs.into_iter().map(|i| i.into()).collect(),
            log_point: val.log_point.map(|log| log.into()),
        }
    }
}

impl TryFrom<pb::Data> for DataFrame {
    type Error = anyhow::Error;

    fn try_from(val: pb::Data) -> Result<Self, Self::Error> {
        Ok(DataFrame {
            logs: val
                .logs
                .into_iter()
                .map(ChangeLog::try_from)
                .collect::<Result<_, _>>()?,
            log_point: val.log_point.map(LogPoint::try_from).transpose()?,
        })
    }
}

#[derive(Clone, Debug)]
pub struct DataAck {
    pub log_point: Option<LogPoint>,
}

impl DataAck {
    pub fn new(log_point: LogPoint) -> anyhow::Result<Self> {
        Ok(Self {
            log_point: Some(log_point),
        })
    }
}

impl From<DataAck> for pb::Ack {
    fn from(val: DataAck) -> Self {
        Self {
            log_point: val.log_point.map(|l| l.into()),
        }
    }
}
