syntax = "proto3";
package protocol;

enum Algorithm {
    AES_128_GCM = 0;
    AES_256_GCM = 1;
    CHACHA20_POLY1305 = 2;
}

message HandshakeRequest {
    bytes signature = 1;
    bytes public_key_salt = 2;
    bytes public_key_hash = 3;
    bytes public_key_data = 4;
    repeated LogPoint log_points = 5;
    string ip = 6;
    string cluster = 7;
    string version = 8;
    string os_name = 9;
    string os_version = 10;
    string os_arch = 11;
    string cpu_name = 12;
    string cpu_vendor = 13;
    uint64 cpu_frequency = 14;
    uint32 cpu_nums = 15;
}

message HandshakeResponse {
    bytes signature = 1;
    bytes public_key_salt = 2;
    bytes public_key_hash = 3;
    bytes public_key_data = 4;
    Algorithm algorithm = 5;
}

message Ping {
    int64 ts = 1;
    repeated LogPoint log_points = 2;
    uint64 uptime = 3;
    double cpu = 4;
    double cpu_current_process = 5;
    double cpu_load_one = 6;
    double cpu_load_five = 7;
    double cpu_load_fifteen = 8;
    uint64 mem_used = 9;
    uint64 mem_free = 10;
    uint64 swap_used = 11;
    uint64 swap_free = 12;
    uint64 disk_used = 13;
    uint64 disk_free = 14;
    uint64 io_read = 15;
    uint64 io_written = 16;
    uint64 net_send = 17;
    uint64 net_received = 18;
    uint64 tls = 19;
    uint64 pv = 20;
    uint64 rt = 21;
    uint64 error = 22;
    string ext_info = 23;
}

message Pong {
    int64 ts = 1;
}

message Data {
    repeated ChangeLog logs = 1;
    LogPoint log_point = 2;
}

message ChangeLog {
    uint64 log_id = 1;
    string cluster_name = 2;
    uint32 log_type = 3;
    uint32 log_action = 4;
    uint64 data_id = 5;
    bytes data = 6;
}

message Ack {
    LogPoint log_point = 1;
}

message Close {
    
}

message LogPoint {
    uint64 log_id = 1;
    uint32 log_type = 2;
}