[package]
authors = ["aigwnet@gmail.com"]
description = "Lite AI Gateway"
edition.workspace = true
name = "aigw"
version = "0.1.0"

[dependencies]
ahash = {version = "0.8"}
aigw-core = {path = "../aigw-core"}
anyhow = {workspace = true}
arc-swap = {workspace = true}
async-trait = {version = "0.1"}
bytes = {version = "1"}
clap = {workspace = true}
dashmap = {workspace = true}
dyn-fmt = {version = "0.4.3"}
hex = {workspace = true}
hostname = {version = "0.4"}
http = {version = "1"}
httpdate = {version = "1"}
ipnet = {version = "2", features = ["serde"]}
itoa = {version = "1"}
lazy_static = {workspace = true}
libc = {workspace = true}
maxminddb = {version = "0.26", features = ["mmap"]}
md5 = {workspace = true}
mime_guess = {version = "2"}
once_cell = {workspace = true}
os_info = {version = "3", default-features = false}
percent-encoding = {version = "2"}
pingora-cache = {workspace = true}
pingora-core = {workspace = true}
pingora-http = {workspace = true}
pingora-limits = {workspace = true}
pingora-load-balancing = {workspace = true}
pingora-proxy = {workspace = true}
regex = {version = "1"}
rusqlite = {version = "0.35"}
rustls = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
sha = {workspace = true}
simple-useragent = {version = "0.1.2"}
substring = {version = "1"}
sysinfo = {version = "0.37"}
time = {workspace = true}
tokio = {workspace = true}
tokio-util = {version = "0.7", features = ["codec"]}
toml = {version = "0.8"}
tracing = {workspace = true}
url = {version = "2"}
urlencoding = {version = "2"}

[target.'cfg(target_os = "linux")'.dependencies]
aya = {workspace = true}
aya-log = {workspace = true}
which = {workspace = true}

[build-dependencies]
anyhow = {workspace = true}
cargo_metadata = {workspace = true}

[package.metadata.deb]
assets = [
  ["target/release/aigw", "/usr/bin/aigw", "755"],
  ["target/aigwe.ebpf", "/etc/aigw/aigw.ebpf", "755"],
  ["target/aigw.1.gz", "/usr/share/man/man1/aigw.1.gz", "644"],
  ["assets/aigw.toml.example", "/etc/aigw/aigw.toml.example", "600"],
  ["assets/aigw.service", "/lib/systemd/system/aigw.service", "644"],
  ["assets/aigw.target", "/lib/systemd/system/aigw.target", "644"],
  ["assets/GeoLite2-Country.mmdb", "/etc/aigw/GeoLite2-Country.mmdb", "600"],
]
changelog = "assets/changelog.txt"
depends = "libc6 (>= 2.23), libgcc1 (>= 1:6.0.1)"
extended-description = """\
 Lite AI Gateway."""
license-file = ["LICENSE.md", "1"]
maintainer-scripts = "assets/deb-scripts"
section = "net"
